### ISSUE TITLE
JSON.parse implementation Node v.0.10.35 cannot parse malformed JSON from coinbase

### ISSUE THREAD

**Issue by travpow** [coinbase/coinbase-exchange-node#1]
[ { id: 'BTC-USD',
    base_currency: 'BTC',
    quote_currency: 'USD',
    base_min_size: 0.01,
    base_max_size: 10000,
    quote_increment: 0.01,
    display_name: 'BTC/USD' } ]

Double-quotes should be used around the component names.

**Comment by defunctzombie** [comment]
Cannot reproduce this issue. A curl of `https://api.exchange.coinbase.com/products` shows everything is proper JSON.
