### ISSUE TITLE
Orderbook Sync only returns { asks: [], bids: [] }

### ISSUE THREAD

**Issue by januszhou** [coinbase/coinbase-exchange-node#11]
Readme example of Orderbook Sync

```
var CoinbaseExchange = require('coinbase-exchange');
var orderbookSync = new CoinbaseExchange.OrderbookSync();
console.log(orderbookSync.book.state());
```

only returns `{ asks: [], bids: [] }`. Should it be return the snapshot of order book?

**Comment by januszhou** [comment]
I found out the issue because of

```
self.publicClient.getProductOrderBook(args, function(err, response, body) {
```

at [orderbook_sync](https://github.com/coinbase/coinbase-exchange-node/blob/master/lib/orderbook_sync.js#L51)
is async, if adding timeout to test it, it would work, 

```
setTimeout(function () {
  book = orderbookSync.book.state();
  console.log(book);
}, 5000);
```

so probably adding promise into  `getProductOrderBook` or wrap the whole `orderbookSync.processMessage` as promise.

**Comment by gagarine** [comment]
The problem is orderbookSync is not returning the parent event.

It should works like that:

```
var orderbookSync = new CoinbaseExchange.OrderbookSync();
orderbookSync.on('message',function(){});
```
