### ISSUE TITLE
Error thrown calling public and authenticated client methods in node-webkit/nwjs

### ISSUE THREAD

**Issue by mnaamani** [coinbase/coinbase-exchange-node#19]
When using the module in node-webkit I encountered an issue related to having multiple contexts:

``` js
<html>
  <body>
    <script>
      var coinbase = require("coinbase-exchange");
      var publicClient = new coinbase.PublicClient();
      publicClient.getProductTicker(function(err, resp, data){
         //this anonymous callback function is created in webkit context
      });
    </script>
  </body>
</html>
```

In the public client and authenticated client, for example:
https://github.com/coinbase/coinbase-exchange-node/blob/3eebdf067d9f154b88f655609f8685405a5a29d6/lib/clients/public.js#L49

..checking if the callback is an `instanceof` `Function` will evaluate to  `false` and thus throwing an error.

The explanation for this behaviour is in the nwjs docs:
https://github.com/nwjs/nw.js/wiki/Differences-of-JavaScript-contexts#working-around-differences-of-contexts

**Comment by mnaamani** [comment]
I've submited a PR with a working solution https://github.com/coinbase/coinbase-exchange-node/pull/18

**Comment by recursion** [comment]
This PR checks out. I tested it and it definitely resolves the issue I was having with node-webkit and coinbase-exchange authenticated calls.
