### ISSUE TITLE
Crossed order book

### ISSUE THREAD

**Issue by gsee** [coinbase/coinbase-exchange-node#4]
If I try to determine the best bid and offer (BBO) prices at a point in time that is between receiving a 'received' message and a 'match' message, I could observe a crossed order book. 

For example, if we see a 'received' message for a buy order that is priced above the best offer, the bid will be [added to the orderbook](https://github.com/coinbase/coinbase-exchange-node/blob/master/lib/orderbook.js#L161) which will create a crossed market until we see a 'match' message (or the 'done' message that follows if we're strictly comparing prices and not excluding zero-quantity orders).

I'm not sure what the best solution is.  I'm not suggesting ignoring 'received' messages because that would lead to having 'match'es involving orders you never saw.  Maybe there could be some sort of pending book?

**Comment by defunctzombie** [comment]
The received message does not become part of the order book. However, it is in fact correct that you see a received message and then a match since that received message (the new incoming order) crosses the book and cases a match. The received order that crossed the book does not itself go on the order book and thus the book is not crossed.

**Comment by gsee** [comment]
Doesn't [line 169 of orderbook.js](https://github.com/coinbase/coinbase-exchange-node/blob/master/lib/orderbook.js#L169) add it to the book?

**Comment by defunctzombie** [comment]
Is the dataset the order book or just tracking order ids? Seems like that is just tracking order ids.

**Comment by gsee** [comment]
Yes, `dataset` is the orderbook.  See [line 163](https://github.com/coinbase/coinbase-exchange-node/blob/master/lib/orderbook.js#L163).  You can test this by comparing the highest bid price to the lowest ask price every time there is a 'received' message.  You'll see that the book gets crossed frequently.
