### ISSUE TITLE
Getting error message 'request timestamp expired' when trying to post an order using Coinbase API

### ISSUE THREAD

**Issue by ramkrishna123** [coinbase/coinbase-exchange-node#42]
Hi,

Using help of https://github.com/coinbase/coinbase-php, i am trying to post order.

It's working correctly in my local server.

But when i upload to our server, we are getting error message 'request timestamp expired'.
Using this url(http://lazybux.com/info.php), you can see our server configuration.
## Here is our code:

require **DIR** . '/vendor/autoload.php';
use Coinbase\Wallet\Client;
use Coinbase\Wallet\Configuration;

$configuration = Configuration::apiKey('Our API Key', 'Our API Secret');
$configuration->setApiUrl(Configuration::SANDBOX_API_URL);
$client = Client::create($configuration);

use Coinbase\Wallet\Enum\Param;
use Coinbase\Wallet\Exception\TwoFactorRequiredException;
use Coinbase\Wallet\Resource\Transaction;
use Coinbase\Wallet\Resource\Checkout;
use Coinbase\Wallet\Value\Money;
use Coinbase\Wallet\Resource\Order;

try {
$order = new Order([
    'name' => 'Order #12',
    'amount' => new Money(4, 'USD'),
]);

$client->createOrder($order);

 echo $bitCoinAddress = $order->getBitcoinAddress();
 $bitCoinUrl = $order->getBitcoinUri();
 ?>
 ?
 }
 catch(Exception $e) {
  echo 'Message: ' .$e->getMessage();
## }

Can you please help us to resolve this issue?
Thank you.

**Comment by mihar** [comment]
Hi, for questions about the Coinbase.com API your best bet is our community forum https://community.coinbase.com/

**Comment by baccredited** [comment]
In my case, on an ubuntu server my clock had drifted out of sync by about 40 seconds. Fixed with this command:
`sudo ntpdate pool.ntp.org`
