### ISSUE TITLE
Update Coinbase Exchange to GDAX 

### ISSUE THREAD

**Issue by lawrencegs** [coinbase/coinbase-exchange-node#46]
Now that gdax.com officially replace exchange.coinbase.com, we should avoid endpoint redirection on the library, and decides on the new name for this library.

**Comment by lawrencegs** [comment]
I created a pull request for the endpoint: https://github.com/coinbase/coinbase-exchange-node/pull/45

**Comment by mihar** [comment]
Thanks @lawrencegs, the transition has now been complete. 

The new package is [gdax](https://www.npmjs.com/package/gdax) and the new repository is [gdax-node](https://github.com/coinbase/gdax-node).
