### ISSUE TITLE
Ethereum support via websocket?

### ISSUE THREAD

**Issue by adamrabie** [coinbase/coinbase-exchange-node#48]
Any idea if the websocket will support ethereum prices in near future?

**Comment by lawrencegs** [comment]
It kinda does, if you change [this line at websocket.js](https://github.com/coinbase/coinbase-exchange-node/blob/master/lib/clients/websocket.js#L8) ETH-BTC or ETH-USD instead of BTC-USD...

**Comment by lawrencegs** [comment]
Or, simply pass ETH-BTC when declaring it...

`var websocket = new CoinbaseExchange.WebsocketClient('ETH-BTC');`

**Comment by mihar** [comment]
Correct, websocket feed works for any supported product.
