### ISSUE TITLE
Failed Authenticated Client on Sandbox URL

### ISSUE THREAD

**Issue by pooleja** [coinbase/coinbase-exchange-node#6]
I tried creating an authenticated client like so:

var authedClient = new CoinbaseExchange.AuthenticatedClient(Env.ACCESS_KEY, Env.SECRET_KEY, Env.PASSPHRASE_KEY, Env.REST_URL);

Where Env.REST_URL is the url to the sandbox API:
https://api-public.sandbox.exchange.coinbase.com

When I try to get the accounts it fails with the timestamp error:

authedClient.getAccounts(function(error, response, data){
...
});

{"statusCode":400,"body":"{\"message\":\"request timestamp expired...

Do any other options need to be set to use this with the sandbox?

**Comment by defunctzombie** [comment]
Just the URL should have to change. Make sure that your computer's time is close to `https://api-public.sandbox.exchange.coinbase.com/time`.

**Comment by defunctzombie** [comment]
Seems that the sandbox machines may have been launched without time syncing enabled. I will double check this to make sure the sandboxes are running on proper time. This is likely the cause of the above error you see.

**Comment by pooleja** [comment]
Yeah, looks like the issue is fixed now... thanks!
