### ISSUE TITLE
Failing to parse getProducts call

### ISSUE THREAD

**Issue by pooleja** [coinbase/coinbase-exchange-node#7]
Looks like the request data is already parsed by the time it hits the JSON.parse(data) call in makeRequestCallback.  I am seeing it throw an exception with the following data being returned:

[ { id: 'BTC-USD',
    base_currency: 'BTC',
    quote_currency: 'USD',
    base_min_size: 0.01,
    base_max_size: 10000,
    quote_increment: 0.01,
    display_name: 'BTC/USD' } ]

SyntaxError: Unexpected token o

This same error is happening with all the product related API calls.  Also I am using the sandbox, so not sure if it is different on the live exchange.

**Comment by gsee** [comment]
This sounds like an issue that was [already fixed](https://github.com/coinbase/coinbase-exchange-node/commit/22e7fb6eec781f6ae02a645f32b929dca70c69d1).  Did you install from the github source?  Are you using version 0.2.0?

$ npm list coinbase-exchange
/current/path
└── coinbase-exchange@0.2.0

**Comment by pooleja** [comment]
Yeah, that was it.  I installed the latest from npmjs.com which was 0.1.0.
